# Generated by Django 4.0.4 on 2022-05-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField(default=0)),
                ('stuname', models.CharField(default='NA', max_length=70)),
                ('stumail', models.EmailField(default='NA', max_length=70)),
                ('stupass', models.CharField(default='NA', max_length=70)),
            ],
        ),
    ]
