# Generated by Django 4.0.4 on 2022-05-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studi', models.IntegerField(default=0)),
                ('stuname', models.CharField(max_length=70, null=True)),
                ('stumail', models.EmailField(max_length=40, null=True)),
                ('stupass', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
