# Generated by Django 4.0.4 on 2022-05-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='commnet',
            field=models.CharField(default='comment not available', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='stuid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stumail',
            field=models.EmailField(default='NA', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='stuname',
            field=models.CharField(default='NA', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='stupass',
            field=models.CharField(default='NA', max_length=70),
        ),
    ]
