# Generated by Django 4.0.4 on 2022-05-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studend',
            new_name='Student',
        ),
    ]
